<?php
/**
 * admin/login.php
 * Login form for the administration panel. This template emits a
 * standard HTML form and includes a CSRF hidden input generated by
 * `csrf_input_field()` from `config.php`.
 *
 * Note: the actual authentication check and session establishment
 * are performed in `admin/auth.php`.
 */

require_once 'config.php';

// If already logged in, redirect to admin panel
if (isset($_SESSION['admin_logged_in']) && $_SESSION['admin_logged_in'] === true) {
    header('Location: index.php');
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            /* use site primary/secondary colors instead of purple */
            background: linear-gradient(135deg, rgba(220,38,38,0.12) 0%, rgba(146,64,14,0.08) 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        
        .login-container {
            background: var(--card-bg); /* warm cream to match admin card surface */
            padding: 2.5rem;
            border-radius: 12px;
            box-shadow: 0 20px 25px -5px rgba(0,0,0,0.3);
            width: 100%;
            max-width: 400px;
        }

        /* Ensure logo badge renders correctly on the standalone login page
           even if external admin CSS is not loaded. Matches admin badge sizing. */
        .logo-badge { display:inline-flex; align-items:center; justify-content:center; padding:6px 10px; border-radius:999px; background: var(--surface-color); box-shadow: 0 6px 20px rgba(16,24,40,0.06); }
        .logo-badge .site-logo-img { height: 40px; width: auto; display: inline-block; vertical-align: middle; }
        
        .login-header {
            text-align: center;
            margin-bottom: 2rem;
        }
        
        .login-header h1 {
            color: var(--text-primary);
            margin-bottom: 0.5rem;
        }
        
        .login-header p {
            color: var(--text-secondary);
        }
        
        .form-group {
            margin-bottom: 1.5rem;
        }
        
        .form-label {
            display: block;
            font-weight: 600;
            margin-bottom: 0.5rem;
            color: var(--text-primary);
        }
        
        .form-input {
            width: 100%;
            padding: 0.75rem;
            border: 1px solid var(--border-color);
            border-radius: 6px;
            font-size: 1rem;
        }
        
        .form-input:focus {
            outline: none;
            border-color: var(--primary-color);
            box-shadow: 0 0 0 3px rgba(220,38,38,0.08);
        }
        
        .btn-login {
            width: 100%;
            padding: 0.875rem;
            background: var(--primary-color);
            color: var(--text-inverse);
            border: none;
            border-radius: 6px;
            font-size: 1rem;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.18s ease;
        }

        .btn-login:hover {
            filter: brightness(0.92);
        }
        
        .alert {
            padding: 1rem;
            border-radius: 6px;
            margin-bottom: 1rem;
            background: rgba(239,68,68,0.08);
            color: var(--error-color);
            border: 1px solid rgba(239,68,68,0.16);
        }
    </style>
</head>
<body>
    <div class="login-container">
                <div class="login-header">
                        <?php
                            $cfile = __DIR__ . '/../data/content.json';
                            $c = file_exists($cfile) ? json_decode(file_get_contents($cfile), true) : [];
                            $logo = $c['images']['logo'] ?? '';
                            $logoUrl = '';
                            if ($logo) { $logoUrl = preg_match('#^https?://#i', $logo) ? $logo : '../uploads/images/'.ltrim($logo, '/'); }
                        ?>
                        <?php if ($logoUrl): ?>
                            <span class="logo-badge" aria-hidden="true"><img class="site-logo-img" src="<?php echo htmlspecialchars($logoUrl); ?>" alt="Admin"></span>
                        <?php else: ?>
                            <h1>🔐 Admin Login</h1>
                        <?php endif; ?>
                        <p>Website Management Panel</p>
                </div>
        
        <?php if (isset($_GET['error'])): ?>
        <div class="alert">
            ❌ Invalid username or password
        </div>
        <?php endif; ?>
        
        <?php if (isset($_GET['logout'])): ?>
        <div class="alert success-alert">
            ✅ You have been logged out successfully
        </div>
        <?php endif; ?>
        
        <form action="auth.php" method="POST">
            <div class="form-group">
                <label class="form-label">Username</label>
                <input type="text" name="username" class="form-input" required autofocus>
            </div>
            
            <div class="form-group">
                <label class="form-label">Password</label>
                <input type="password" name="password" class="form-input" required>
            </div>
            
            <?php // include CSRF token inside the login form so it is submitted ?>
            <?php echo csrf_input_field(); ?>
            <button type="submit" class="btn-login">Login</button>
        </form>
        
    <p style="text-align: center; margin-top: 1.5rem; color: var(--text-secondary); font-size: 0.875rem;">
            Forgot password? Contact your administrator
        </p>
    </div>
</body>
</html>
