<?php
/**
 * admin/login.php
 * Login form for the administration panel. This template emits a
 * standard HTML form and includes a CSRF hidden input generated by
 * `csrf_input_field()` from `config.php`.
 *
 * Note: the actual authentication check and session establishment
 * are performed in `admin/auth.php`.
 */

require_once 'config.php';

// If already logged in, redirect to admin panel
if (isset($_SESSION['admin_logged_in']) && $_SESSION['admin_logged_in'] === true) {
    header('Location: index.php');
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        
        .login-container {
            background: white;
            padding: 2.5rem;
            border-radius: 12px;
            box-shadow: 0 20px 25px -5px rgba(0,0,0,0.3);
            width: 100%;
            max-width: 400px;
        }
        
        .login-header {
            text-align: center;
            margin-bottom: 2rem;
        }
        
        .login-header h1 {
            color: #1e293b;
            margin-bottom: 0.5rem;
        }
        
        .login-header p {
            color: #64748b;
        }
        
        .form-group {
            margin-bottom: 1.5rem;
        }
        
        .form-label {
            display: block;
            font-weight: 600;
            margin-bottom: 0.5rem;
            color: #1e293b;
        }
        
        .form-input {
            width: 100%;
            padding: 0.75rem;
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            font-size: 1rem;
        }
        
        .form-input:focus {
            outline: none;
            border-color: #2563eb;
            box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.1);
        }
        
        .btn-login {
            width: 100%;
            padding: 0.875rem;
            background: #2563eb;
            color: white;
            border: none;
            border-radius: 6px;
            font-size: 1rem;
            font-weight: 600;
            cursor: pointer;
            transition: background 0.2s;
        }
        
        .btn-login:hover {
            background: #1d4ed8;
        }
        
        .alert {
            padding: 1rem;
            border-radius: 6px;
            margin-bottom: 1rem;
            background: #fee2e2;
            color: #991b1b;
            border: 1px solid #fca5a5;
        }
    </style>
</head>
<body>
    <div class="login-container">
                <div class="login-header">
                        <?php
                            $cfile = __DIR__ . '/../data/content.json';
                            $c = file_exists($cfile) ? json_decode(file_get_contents($cfile), true) : [];
                            $logo = $c['images']['logo'] ?? '';
                            $logoUrl = '';
                            if ($logo) { $logoUrl = preg_match('#^https?://#i', $logo) ? $logo : '../uploads/images/'.ltrim($logo, '/'); }
                        ?>
                        <?php if ($logoUrl): ?>
                            <img src="<?php echo htmlspecialchars($logoUrl); ?>" alt="Admin" style="height:72px;margin-bottom:0.5rem">
                        <?php else: ?>
                            <h1>🔐 Admin Login</h1>
                        <?php endif; ?>
                        <p>Website Management Panel</p>
                </div>
        
        <?php if (isset($_GET['error'])): ?>
        <div class="alert">
            ❌ Invalid username or password
        </div>
        <?php endif; ?>
        
        <?php if (isset($_GET['logout'])): ?>
        <div class="alert" style="background: #d1fae5; color: #065f46; border-color: #6ee7b7;">
            ✅ You have been logged out successfully
        </div>
        <?php endif; ?>
        
        <form action="auth.php" method="POST">
            <div class="form-group">
                <label class="form-label">Username</label>
                <input type="text" name="username" class="form-input" required autofocus>
            </div>
            
            <div class="form-group">
                <label class="form-label">Password</label>
                <input type="password" name="password" class="form-input" required>
            </div>
            
            <?php // include CSRF token inside the login form so it is submitted ?>
            <?php echo csrf_input_field(); ?>
            <button type="submit" class="btn-login">Login</button>
        </form>
        
        <p style="text-align: center; margin-top: 1.5rem; color: #64748b; font-size: 0.875rem;">
            Forgot password? Contact your administrator
        </p>
    </div>
</body>
</html>
